variable "resource_group_name" {}
variable "environment" {}
variable "department" {}
variable "function_name" {}
variable "env_shorthand" {}
variable "k8s_service_principal_name" {}
variable "aks_name" {}
variable "aks_node_count" {}
variable "aks_node_size" {}
variable "vault_resource_group_name" {}
variable "aks_deployment_secret_name" {}
variable "key_vault_name" {}