variable "resource_group_name" {}
variable "environment" {}
variable "department" {}
variable "function_name" {}
variable "virtual_network_name" {}
variable "security_group_name" {}
variable "subnet_name" {}
variable "public_ip_name" {}
variable "network_interface_name" {}
variable "ip_config_name" {}
variable "virtual_machine_name" {}
variable "virtual_machine_size" {}
variable "vm_os_disk_name" {}
variable "vm_data_disk_name" {}
variable "vm_disk_replication_type" {}
variable "data_disk_size_in_gb" {}
variable "image_name" {}
variable "image_resource_group" {}