variable "resource_group_name" {}
variable "virtual_network_name" {}
variable "frontend_subnet_name" {}
variable "backend_subnet_name" {}
variable "public_ip_name" {}
variable "gateway_name" {}
variable "gateway_sku_name" {}
variable "gateway_sku_tier" {}
variable "gateway_sku_capacity" {}
variable "frotend_port" {}
variable "frontend_protocol" {}
variable "backend_port" {}
variable "backend_protocol" {}
variable "cookie_affinity" {}
variable "request_timetout" {}
variable "routing_rule_type" {}